Region.delete_all
na = Region.create("Name" => "North America", "Picture_url" => "http://th07.deviantart.net/fs71/PRE/f/2012/198/b/a/the_united_states_of_america_by_wire4k-d57jle2.png")
eu = Region.create("Name" => "Europe", "Picture_url" => "http://www.mappi.net/img/carte_europe/carte-europe-ville.jpg")
ca = Region.create("Name" => "Carribbean", "Picture_url" => "http://www.worldatlas.com/webimage/countrys/caribnew.gif")
sa = Region.create("Name" => "Central and South America", "Picture_url" => "http://www.gilgordon.com/images/pics/map_samerica.gif")
as = Region.create("Name" => "Asia", "Picture_url" => "http://www.asap-asia.org/images/asia-map-dr-shilpa.jpg")
af = Region.create("Name" => "Africa", "Picture_url" => "http://www.worldatlas.com/webimage/countrys/africapolitmap.jpg")
au = Region.create("Name" => "Australia", "Picture_url" => "http://www.worldatlas.com/webimage/countrys/oceania/lgcolor/aunewcolor.gif")
an = Region.create("Name" => "Antartica", "Picture_url" => "http://www.mapsofworld.com/antarctica/maps/antarctica-map.gif")

Country.delete_all
denmark = Country.create("Name" => "Denmark", "Picture_url" => "http://toptravellists.net/wallpapers/2012/05/Sea-City-Landscape-Denmark-485x728.jpg", "Region_id" => eu.id)
italy = Country.create("Name" => "Italy", "Picture_url" => "http://www.grandtoursorrentocoast.com/wp-content/uploads/2013/04/sorrento-710x450.jpg", "Region_id" => eu.id)
nicaragua = Country.create("Name" => "Nicaragua", "Picture_url" => "http://www.clipbyconnect.com/wp-content/uploads/2013/03/resort-spa-mukul.jpg", "Region_id" => sa.id)

Trip.delete_all
de = Trip.create("Name" => "Denmark", "Picture_url" => "http://www.hdrone.com/wp-content/uploads/2012/08/Jim-Nix-Sunset-at-Nyhavn-Copenhagen-Denmark.jpg", "Description" => "Start the Kellogg experience with a different kind of “class” before the real class begins – this version includes a black tie ball, elegant restaurants, an opera, castle / palace tours, a winery tour, and spreading diplomacy with cocktails and dinner with the US Ambassador to Denmark.  The KWEST Vienna/Copenhagen trip is sure to kick the Kellogg experience off on the right foot.  Tuxes and gowns required!  You stay classy Kellogg. ", "Itinerary_url" => "https://scontent-a-ord.xx.fbcdn.net/hphotos-frc3/t1.0-9/10372044_833414473354006_4809543385624279227_n.jpg", "Budget_url" => "https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-prn2/t1.0-9/10270591_833417140020406_512752289419888390_n.jpg", "Priority_url" => "https://scontent-b-ord.xx.fbcdn.net/hphotos-ash4/t1.0-9/10268531_833417143353739_7009178668934387928_n.jpg", "Country_id" => denmark)
it = Trip.create("Name" => "Italy", "Picture_url" => "http://www.adventuresbydisney.com/media/abd/europe/italy-vacations/venice-gondolas-canal-night.jpg", "Description" => "Vacation as Italians do: Go south to lay on the beautiful blue beaches of Southern Italy and discover the authentic sources of the delicious red sauce Italian food exported around the world. After touring the sites in Rome, we’ll enjoy the beaches of Capri and the Amalfi Coast before exploring the unique history and culture of Sicily. Cannoli, anyone?", "Itinerary_url" => "https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-prn2/t1.0-9/10308214_833419183353535_1775209901536675737_n.jpg", "Budget_url" => "https://scontent-a-ord.xx.fbcdn.net/hphotos-prn1/t1.0-9/10340007_833419170020203_4773359493273927829_n.jpg", "Priority_url" => "https://scontent-a-ord.xx.fbcdn.net/hphotos-ash3/t1.0-9/10320458_833419160020204_7670493832866814553_n.jpg", "Country_id" => italy)
ni = Trip.create("Name" => "Nicaragua", "Picture_url" => "http://images.nationalgeographic.com/wpf/media-live/photos/000/027/cache/nicaragua_2732_600x450.jpg", "Description" => "Discover the true meaning of adventure in Nicaragua. Sled down charcoal slopes. Zipline through a cloud forest. Kayak in a tidal estuary. Hike up an active volcano at night! Be a superhero by helping local Nicaraguans before heading to a real bat cave!  Oh yeah, and rage the whole time!", "Itinerary_url" => "https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-prn1/t1.0-9/1001981_833420693353384_5639274737202412899_n.jpg", "Budget_url" => "https://scontent-b-ord.xx.fbcdn.net/hphotos-ash3/t1.0-9/10291062_833420683353385_8670180194906832593_n.jpg", "Priority_url" => "https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-frc3/t1.0-9/10363882_833420680020052_6998272330870577804_n.jpg", "Country_id" => nicaragua)

Itinerary.delete_all
denmarkitinerary = Itinerary.create("Day" => "1", "City" => "Chicago-Vienna", "Activity" => "Day 1 means travel day!  How better to get acquainted with your 25 new best friends while learning both Austrian and Danish than on an overnight flight?!", "Hotel" => "Sleep on the plane", "Transportation" => "Flight to Vienna", "Itinerary_url" => "https://scontent-a-ord.xx.fbcdn.net/hphotos-frc3/t1.0-9/10372044_833414473354006_4809543385624279227_n.jpg", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "2", "City" => "Vienna", "Activity" => "Hit the ground running with a look around Vienna -- checking out all the historical and modern sights! If you need a nap, we can squeeze one in here, but this day is all about getting familiar with the city -- both the day and night life!", "Hotel" => "Levante Parliament, 2 people per room, 2 beds per room", "Transportation" => "Private bus and boat tour", "Itinerary_url" => "", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "3", "City" => "Vienna ", "Activity" => "Who needs Napa when you've got the Wachau Valley. We’ll tour the glorious abbey, eat lunch, taste wine, and spend the afternoon meandering down the river to Krems by bike or boat. But that's not all - at night, we’ll be dressed up in our fanciest ballroom attire, enjoy an upscale dinner and then dance the night away with the über-chic of Vienna.", "Hotel" => "Levante Parliament, 2 people per room, 2 beds per room", "Transportation" => "Private bus to and from Wachau Valley", "Itinerary_url" => "", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "4", "City" => "Vienna", "Activity" => "Hello Mountains! Enjoy the finest scenery with a glorious hike in the Alps. After mailing some postcards, we'll have one last evening of fun in Vienna.", "Hotel" => "Levante Parliament, 2 people per room, 2 beds per room", "Transportation" => "None", "Itinerary_url" => "", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "5", "City" => "Vienna-Copenhagen", "Activity" => "Rise and shine as we head off to Copenhagen. Paddle your way through the beautiful city on kayaks. Want a once in a lifetime experience? How about some cocktails with an Ambassador. Check that one off the list.", "Hotel" => "Copenhagen Star Hotel, 2 people per room, 2 beds per room", "Transportation" => "Bus to Vienna airport, flight to Copenhagen, and bus to hotel in Copenhagen          ", "Itinerary_url" => "", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "6", "City" => "Copenhagen", "Activity" => "Castle Day and Nautical Night! Confused? Enjoy some truly historic Danish castles during the day, a brewery tour in the afternoon, and dress up in your most nautical gear for drinks on the water. Things sound a little fishy, we know.", "Hotel" => "Copenhagen Star Hotel, 2 people per room, 2 beds per room", "Transportation" => "Private bus to castle", "Itinerary_url" => "", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "7", "City" => "Copenhagen", "Activity" => "Give back at our service project via the US Ambassador and enjoy the beach with your closest friends in the afternoon", "Hotel" => "Copenhagen Star Hotel, 2 people per room, 2 beds per room", "Transportation" => "Private bus to community service project", "Itinerary_url" => "", "Trip_id" => de)
denmarkitinerary = Itinerary.create("Day" => "8", "City" => "Copenhagen-Chicago", "Activity" => "SLEEP! You're going to need to rest up before CIM hits!", "Hotel" => "Sleep on the plane", "Transportation" => "Bus to airport", "Itinerary_url" => "", "Trip_id" => de)

Contact.delete_all
Contact.create("Type" => "Activity", "Location" => "Wachau Valley", "Company_name" => "Vienna Explorer ", "Contact" => "", "Address" => "Franz Josefs Kai 45; 1010 Wien", "Phone_number" => "+43 699 10 62 62 09", "Website" => "http://www.viennaexplorer.com/about-us/#contactForm", "Trip_id" => de)
Contact.create("Type" => "Activity", "Location" => "Vienna Alps", "Company_name" => "Viator: Vienna Woods and Mayerling Half Day Trip", "Contact" => "", "Address" => "Internet based", "Phone_number" => "(888) 651-9785", "Website" => "http://www.viator.com/tours/Vienna/Vienna-Woods-and-Mayerling-Half-Day-Trip/d454-3585AT004VS", "Trip_id" => de)
Contact.create("Type" => "Hotel", "Location" => "Copenhagen ", "Company_name" => "Copenhagen Star Hotel", "Contact" => "", "Address" => "Colbjørnsensgade 13, 1652 Copenhagen V, Denmark, 1652 V Copenhagen, DK", "Phone_number" => "+45 33 22 11 00", "Website" => "http://www.copenhagenstar.dk/", "Trip_id" => de)
Contact.create("Type" => "Activity", "Location" => "Copenhagen ", "Company_name" => "Cocktails with US Ambassador", "Contact" => "Emily Ronek", "Address" => "Dag Hammarskjölds Allé 24 2100 København Ø.", "Phone_number" => "+45 33 41 71 00 ", "Website" => "http://denmark.usembassy.gov/contact.html", "Trip_id" => de)
Contact.create("Type" => "Activity", "Location" => "Copenhagen ", "Company_name" => "Kayak Republic", "Contact" => "", "Address" => "Borskaj 12, Copenhagen 1221, Denmark", "Phone_number" => "+45 30498620", "Website" => "http://kayakrepublic.dk/", "Trip_id" => de)
Contact.create("Type" => "Activity", "Location" => "Copenhagen ", "Company_name" => "Carlsberg Brewery Tour", "Contact" => "", "Address" => "Gamle Carlsberg Vej 11 1799 Copenhagen V", "Phone_number" => "+45 3327 1282", "Website" => "http://www.visitcarlsberg.dk/experiences/pages/guidedtours.aspx", "Trip_id" => de)
Contact.create("Type" => "Service", "Location" => "Copenhagen ", "Company_name" => "US Embassy Service Project", "Contact" => "Emily Ronek", "Address" => "Dag Hammarskjölds Allé 24 2100 København Ø.", "Phone_number" => "+45 33 41 71 00 ", "Website" => "http://denmark.usembassy.gov/contact.html", "Trip_id" => de)
Contact.create("Type" => "Hospital", "Location" => "Copenhagen ", "Company_name" => "Frederiksberg Hospital", "Contact" => "", "Address" => "Nordre Fasanvej 57  2000 Frederiksberg", "Phone_number" => "+45 38 16 38 16", "Website" => "http://www.frederiksberghospital.dk", "Trip_id" => de)
Contact.create("Type" => "Hotel", "Location" => "Vienna", "Company_name" => "The Levante Parliament", "Contact" => "", "Address" => "Auerspergstraße 9, Vienna", "Phone_number" => "+43 1 228 28 - 0; +43 1 535 45 15-50", "Website" => "http://www.thelevante.com/parliament/en/home.html", "Trip_id" => de)
Contact.create("Type" => "Hospital", "Location" => "Vienna", "Company_name" => "General Hospital of Vienna", "Contact" => "", "Address" => "Währinger Gürtel 18-20, 1090 Wien", "Phone_number" => "+43 1 404 00-0", "Website" => "http://www.akhwien.at/", "Trip_id" => de)



# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
